REM Build Bat File
REM Precheck the Resource 
"C:\Program Files\MRE SDK V3.0.00\tools\ResEditor\CmdShell.exe" save  "D:\MyGitHub\Textvp_v2\Textvp_v2.vcproj"
REM Copmile c file 
"C:\Program Files (x86)\CodeSourcery\Sourcery_CodeBench_Lite_for_ARM_EABI\Bin\arm-none-eabi-gcc" -c -fpic -g -mcpu=arm7tdmi-s -fvisibility=hidden -mthumb -mlittle-endian -O2 -D__MRE_COMPILER_GCC__ -fno-exceptions -fno-non-call-exceptions -o "D:\MyGitHub\Textvp_v2\arm\gccmain.o" -c "C:\Program Files\MRE SDK V3.0.00\lib\MRE30\src\gccmain.c"      -D _MINIGUI_LIB_ -D _USE_MINIGUIENTRY -D _NOUNIX_ -D _FOR_WNC -D __MRE_SDK__ -D   __MRE_VENUS_NORMAL__  -D  __MMI_MAINLCD_240X320__ -I "C:\Program Files\MRE SDK V3.0.00\include" -I "C:\Program Files\MRE SDK V3.0.00\include\service" -I "C:\Program Files\MRE SDK V3.0.00\include" -I "C:\Program Files\MRE SDK V3.0.00\include\service" -I "D:\MyGitHub\Textvp_v2\include" -I "D:\MyGitHub\Textvp_v2\include\service" -I "D:\MyGitHub\Textvp_v2\include\component" -I "D:\MyGitHub\Textvp_v2\ResID" -I "D:\MyGitHub\Textvp_v2\src\app\widget" -I "D:\MyGitHub\Textvp_v2\src\app\launcher" -I "D:\MyGitHub\Textvp_v2\src\app\wallpaper" -I "D:\MyGitHub\Textvp_v2\src\app\screen_lock" -I "D:\MyGitHub\Textvp_v2\include\service" -I "D:\MyGitHub\Textvp_v2\include\component" -I "D:\MyGitHub\Textvp_v2\include\service" -I "D:\MyGitHub\Textvp_v2\src\framework" -I "D:\MyGitHub\Textvp_v2\src\framework\ui_core\base" -I "D:\MyGitHub\Textvp_v2\src\framework\ui_core\mvc" -I "D:\MyGitHub\Textvp_v2\src\framework\ui_core\pme" -I "D:\MyGitHub\Textvp_v2\src\framework\mmi_core" -I "D:\MyGitHub\Textvp_v2\src\ui_engine\vrt\interface" -I "D:\MyGitHub\Textvp_v2\src\component" -I "D:\MyGitHub\Textvp_v2\src\ui_engine\framework\xml" -I "D:\MyGitHub\Textvp_v2"
REM Copmile c file 
"C:\Program Files (x86)\CodeSourcery\Sourcery_CodeBench_Lite_for_ARM_EABI\Bin\arm-none-eabi-gcc" -c -fpic -g -mcpu=arm7tdmi-s -fvisibility=hidden -mthumb -mlittle-endian -O2 -D__MRE_COMPILER_GCC__ -fno-exceptions -fno-non-call-exceptions -o "D:\MyGitHub\Textvp_v2\arm\Textvp_v2.o" -c "d:\MyGitHub\Textvp_v2\Textvp_v2.c"      -D _MINIGUI_LIB_ -D _USE_MINIGUIENTRY -D _NOUNIX_ -D _FOR_WNC -D __MRE_SDK__ -D   __MRE_VENUS_NORMAL__  -D  __MMI_MAINLCD_240X320__ -I "C:\Program Files\MRE SDK V3.0.00\include" -I "C:\Program Files\MRE SDK V3.0.00\include\service" -I "C:\Program Files\MRE SDK V3.0.00\include" -I "C:\Program Files\MRE SDK V3.0.00\include\service" -I "D:\MyGitHub\Textvp_v2\include" -I "D:\MyGitHub\Textvp_v2\include\service" -I "D:\MyGitHub\Textvp_v2\include\component" -I "D:\MyGitHub\Textvp_v2\ResID" -I "D:\MyGitHub\Textvp_v2\src\app\widget" -I "D:\MyGitHub\Textvp_v2\src\app\launcher" -I "D:\MyGitHub\Textvp_v2\src\app\wallpaper" -I "D:\MyGitHub\Textvp_v2\src\app\screen_lock" -I "D:\MyGitHub\Textvp_v2\include\service" -I "D:\MyGitHub\Textvp_v2\include\component" -I "D:\MyGitHub\Textvp_v2\include\service" -I "D:\MyGitHub\Textvp_v2\src\framework" -I "D:\MyGitHub\Textvp_v2\src\framework\ui_core\base" -I "D:\MyGitHub\Textvp_v2\src\framework\ui_core\mvc" -I "D:\MyGitHub\Textvp_v2\src\framework\ui_core\pme" -I "D:\MyGitHub\Textvp_v2\src\framework\mmi_core" -I "D:\MyGitHub\Textvp_v2\src\ui_engine\vrt\interface" -I "D:\MyGitHub\Textvp_v2\src\component" -I "D:\MyGitHub\Textvp_v2\src\ui_engine\framework\xml" -I "D:\MyGitHub\Textvp_v2"
REM Link app 
"C:\Program Files (x86)\CodeSourcery\Sourcery_CodeBench_Lite_for_ARM_EABI\Bin\arm-none-eabi-gcc" -o "D:\MyGitHub\Textvp_v2\Textvp_v2.axf"  "D:\MyGitHub\Textvp_v2\arm\gccmain.o"  "D:\MyGitHub\Textvp_v2\arm\Textvp_v2.o" -fpic -msvr4-struct-return -pie  -T "C:\Program Files\MRE SDK V3.0.00\lib\MRE30\armgcc\scat.ld" -l:"C:\Program Files\MRE SDK V3.0.00\lib\MRE30\armgcc\percommon.a" -l:"C:\Program Files\MRE SDK V3.0.00\lib\MRE30\armgcc\perfile.a" -l:"C:\Program Files\MRE SDK V3.0.00\lib\MRE30\armgcc\persysfile.a" -l:"C:\Program Files\MRE SDK V3.0.00\lib\MRE30\armgcc\persysstorage.a"
REM Pack resource to app 
"C:\Program Files\MRE SDK V3.0.00\tools\ResEditor\CmdShell.exe" pack -silent -resolution 240x320 -o "D:\MyGitHub\Textvp_v2\Textvp_v2.pkd" -e AXF "D:\MyGitHub\Textvp_v2\Textvp_v2.vcproj" "D:\MyGitHub\Textvp_v2\Textvp_v2.axf"
REM Add tag infromation 
"C:\Program Files\MRE SDK V3.0.00\tools\PackDigist.exe" "D:\MyGitHub\Textvp_v2\Textvp_v2.vcproj" "Textvp_v2" "0.1.0" "RDZDX" "0" "NotSupportBg" "Not Support rotate" "Textvp_v2" "Textvp_v2" "Textvp_v2" "9246012102087182" "content" " File SysFile SysStorage" "vxp" "GCC" "PKD" "UnCompress" "NoVPI" "Adaptable" "15728960" "UnSysMemAble" "
    " "-1" "UNPUSH" "-1" ""  "UnAutoStart"  "UnTransferImg" "NoIdleShortcut"  D:\MyGitHub\Textvp_v2\arm D:\MyGitHub\Textvp_v2\build.log

